language: go
sudo: false
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/fatih/structs
before_script:
- go vet ./...
os:
- osx
go:
- tip
script:
- $HOME/gopath/src/github.com/britannic/blacklist/testcoverage
env:
  global:
  - secure: VaM58xmuN+dJV5DEZLVTcqXyNr/xlQCmZauXanTTjWe75obfOemAKCR7xbIkrnyfyYOkmKGV9nCPIveasGe/jqmOWGPfSAJsAfCEGupJqkn+UyGWngdLiIYnPcTycsFYbrFq48/F38Yc4L4RzX/3cy/l62Wre54W79ynxObHxeLRs32a/oAEBJN3kQuNJKmUr8Erdm5kaydYL++LX2yMyE32er61hUdawVB/AERQ913Tuse6vibfjwQP4wyvqth/uYEurbBhRoM/3Tp7845IA5OgLLTEOeWl27307PV+Tdr+N156fJx8Qhj6oDkcvStV/Ts17LbPemEbE0BJM3mn17eUjOvb+g3pkei+kTWGBxd4m30eYK4VG8iWs/zIqPxUQDtPBE5+MoQjRE984iTO+gGd+kCy6/yGJePsaAuNSxzK3c0XUBL0luGePdNlawF/NTek3yRHci36N72tcbcE6aPlYSa2RbrgJ7lXoSXqQle0t9UXYjemplkpgxf4iFZyoIqaXpHvGeYMxTr7ocgbVgMS3eDZZlC52pLcC6rHtdaFYbjy8xn5qMkEAUR1QfucHFvo6l5Us+GzaK6780xTEet7To3FNMsc0Gz3sYSkkykL+IES9hJyYpiK/HeVdcMGBiQ2BjnWgu//i0Bl7qTE4Lzps9XJLghLk3Nw2UuNCPk=
